# Modified by: BenoÃ®t H.Dicaire
# Source: https://starship.rs/config
# https://www.nerdfonts.com/cheat-sheet?set=nf-pl-
# https://gist.github.com/deepanchal/415e78646aaf5e57e10490d01ad90109
# https://starship.rs/config/#prompt

scan_timeout = 40
command_timeout = 2000
# add_newline = true

[palettes.bhd]
# Overwrite existing color
blue = '21'
# Define new color
mustard = '#af8700'

[line_break]
disabled = true

[localip]
disabled = false
ssh_only = true
format = '@[$localipv4](bold red) '

[hostname]
disabled = false
ssh_only = true
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'

[os]
disabled = true
format = "on [($name )]($style)"
#format = "on [($name)($symbol) ($version)]($style)"
style = "bold blue"

[os.symbols]
Alpine = "ğŸ”ï¸ "
Amazon = "ğŸ™‚ "
Arch = "ğŸ—ï¸ "
CentOS = "ğŸ’  "
Debian = "ğŸŒ€ "
DragonFly = "ğŸ‰ "
Fedora = "ğŸ© "
FreeBSD = "ğŸ˜ˆ "
Gentoo = "ğŸ—œï¸ "
HardenedBSD = "ğŸ›¡ï¸ "
Illumos = "ğŸ¦ "
Linux = "ğŸ§ "
Macos = "ïŒ‚ "
Manjaro = "ğŸ¥­ "
Mint = "ğŸŒ¿ "
NetBSD = "ğŸš© "
OpenBSD = "ğŸ¡ "
openSUSE = "ğŸ¦ "
OracleLinux = "ğŸ¦´ "
Pop = "ğŸ­ "
Raspbian = "ğŸ“ "
Redhat = "ğŸ© "
RedHatEnterprise = "ğŸ© "
SUSE = "ğŸ¦ "
Ubuntu = "ğŸ¯ "
Unknown = "â“ "
Windows = "ğŸªŸ "

format = """
[â–‘â–’â–“](#a3aed2)\
[ îœ‘ ](bg:#a3aed2 fg:#090c0c)\
[î‚´](bg:#769ff0 fg:#a3aed2)\
$directory\
[î‚´](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[î‚´](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[î‚´](fg:#212736 bg:#1d2230)\
$time\
[î‚´ ](fg:#1d2230)\
\n$character"""

################################################################################
## Custom Commands
################################################################################
[custom.git_server]
#disabled = true
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL="ïˆ "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL="ïŠ– "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL="ï…± "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL="ï¡ "
else
    GIT_REMOTE_SYMBOL="ï‡’ "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
style = "white"
format = '[$output]($style) '



[character]
success_symbol = "[âœ](grey)"
error_symbol = "[âœ](bold red)"
vimcmd_symbol = "[â®](bold green)" #The format string used before the text input if the shell is in vim normal mode.
vimcmd_replace_one_symbol= "[â®](bold purple)" #The format string used before the text input if the shell is in vim replace_one mode.
vimcmd_replace_symbol= "[â®](bold purple)" #The format string used before the text input if the shell is in vim replace mode.
vimcmd_visual_symbol= "[â®](bold yellow)"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
#style = "blue"
format = "[ $path ]($style)"
truncation_length = 20
truncation_symbol = "â€¦/"
truncate_to_repo = false
read_only = " ï ½"
home_symbol = " ~"

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
#"/Volumes/Tarmac/Code/w3" = "ïœ˜ "
#"/Volumes/Tarmac/Code" = "http://github.com/bhdicaire"

[aws]
disabled = true
symbol = "îŒ½  "
format = '\[AWS: [$profile/($region)]($style)\]'
style = 'bold orange'

[azure]
disabled = true
symbol = 'ï´ƒ '
format = 'on [$symbol($subscription)] with [$symbol($username)](($style) '
style = 'blue bold'

[battery]
disabled = true

[buf]
symbol = "ï’ "

[bun]
disabled = true
format = 'via [ğŸ” $version](bold green) '

[c]
symbol = "î˜ "

[cmd_duration]
# shows how long the last command took to execute. The module will be shown only if the command took longer than two seconds , or the min_time config value, if it exists
# min_time = 500
min_time = 2000
format = 'underwent [$duration](bold yellow)'

[cobol]
disabled = true

[conda]
format = '[$symbol$environment](dimmed green) '

[container]
format = '[$symbol \[$name\]]($style) '
style = 'bold red dimmed'

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[dotnet]
disabled = true

[elixir]
disabled = true
symbol = "î‰µ "

[elm]
disabled = true
symbol = "î˜¬ "

[gcloud]
symbol = 'ï¸ğŸ‡¬ï¸ '
[gcloud.region_aliases]
us-central1 = 'uc1'
asia-northeast1 = 'an1'

[git_branch]
symbol = "ï˜"
format = '[$symbol $branch ]($style)'
style = "fg:#769ff0 bg:#394260"
#ignore_branches = ['master', 'main']

[git_status]
format = '([\[$all_status\]]($style) )'
style = "fg:#769ff0 bg:#394260"
ahead = 'â‡¡${count}'  # Disabled in the prompt format $ahead_behind
behind = 'â‡£${count}' # Disabled in the prompt format $ahead_behind
conflicted = 'ğŸ³'
deleted = '[âœ˜](red) '
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
modified = '[* ](blue)'
renamed = 'ğŸ‘…'
staged = '[+$count](green)'
stashed = 'ğŸ“¦ '
untracked = ""       # Disabled
#untracked = 'ğŸ¤· '
up_to_date = '[âœ“ ](blue)'
# windows_starship = '/mnt/c/Users/username/scoop/apps/starship/current/starship.exe'

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[git_state]
disabled = true
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_metrics]
disabled = true
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[golang]
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
# format = 'via [ğŸğŸ’¨ $version](bold cyan) '
symbol = "ï³‘"
style = "bg:#212736"

[guix_shell]
disabled = true
format = 'via [ğŸ‚](yellow bold) '

[haskell]
symbol = "î· "

[haxe]
disabled = true
symbol = "âŒ˜ "

[helm]
format = 'via [âˆ $version](bold white) '

[hg_branch]  # Mercurial
disabled = true
format = 'on [ğŸŒ± $branch](bold purple)'
truncation_length = 4
truncation_symbol = ''

[java]
disabled = true
symbol = "î‰– "

[jobs]
symbol = '+ '
number_threshold = 2
symbol_threshold = 1

[julia]
disabled = true
symbol = "î˜¤ "

[kubernetes]
disabled = true
detect_files = ['k8s']
format = 'on [â›µ ($user on )($cluster in )$context \($namespace\)](dimmed green) '

[kubernetes.context_aliases]
'dev.local.cluster.k8s' = 'dev'
'.*/openshift-cluster/.*' = 'openshift'
'gke_.*_(?P<var_cluster>[\\w-]+)' = 'gke-$var_cluster'

[kubernetes.user_aliases]
'dev.local.cluster.k8s' = 'dev'
'root/.*' = 'root'

[lua]
format = 'via [ğŸŒ• $version](bold blue) '

[memory_usage]
disabled = true
threshold = -1
symbol = ' '
style = 'bold dimmed green'

[meson]
disabled = true
truncation_symbol = '--'
symbol = ' '
style = 'bold dimmed green'

[nim]
disabled = true
symbol = "ïš¤ "

[nix_shell]
disabled = true
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
format = 'via [â˜ƒï¸ $state( \($name\))](bold blue) '

[nodejs]
symbol = "îœ˜ "

[ocaml]
disabled = true
format = 'via [ğŸª $version]($style) '

[opa]
format = 'via [â›‘ï¸  $version](bold red) '

[openstack]
disabled = true
format = 'on [$symbol$cloud(\($project\))]($style) '
style = 'bold yellow'
symbol = 'â˜ï¸ '

[package]
format = 'via [ğŸ $version](208 bold) '

[perl]
format = 'via [ğŸ¦ª $version]($style) '

[php]
disabled = true
format = 'via [ğŸ”¹ $version](147 bold) '

[pulumi] #By default the Pulumi version is not shown, since it takes an order of magnitude longer to load then most plugins (~70ms)
disabled = true
format = '[ğŸ›¥ ($version )$stack]($style) '

[purescript]
disabled = true
format = 'via [$symbol$version](bold white)'

[python]
format = "[$virtualenv]($style) "
python_binary = 'python3' # Only use the `python3` binary to get the version.
# python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']
# Display the version of python from inside a local venv.
# Note this will only work when the venv is inside the project and it will only
# work in the directory that contains the venv dir but maybe this is ok?

[rlang]
format = 'with [ğŸ“ $version](blue bold) '

[raku]
disabled = true
format = 'via [ğŸ¦ª $version]($style) '

[red]
disabled = true
symbol = 'ğŸ”´ '

[ruby]
symbol = "î‘ "

[rust]
format = 'via [âš™ï¸ $version](red bold)'

[scala]
disabled = true
symbol = "îœ· "

[shell]
disabled = true
fish_indicator = 'ïœ¹'
powershell_indicator = 'ï‘ _'
unknown_indicator = 'mystery shell'
style = 'cyan bold'

[shlvl]
disabled = false
format = '$shlvl level(s) down'
threshold = 3

[singularity]
disabled = true
format = '[ğŸ“¦ \[$env\]]($style) '

[spack]
disabled = true
format = '[$symbol$environment](dimmed blue) '

[status]
disabled = true
style = 'bg:blue'
symbol = 'ğŸ”´ '
success_symbol = 'ğŸŸ¢ SUCCESS'
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true

[sudo]
disabled = true
style = 'bold green'
symbol = 'ğŸ‘©â€ğŸ’» '
allow_windows = true

[swift]
disabled = true
format = 'via [ğŸ  $version](red bold)'

[terraform] # slow
disabled = true
format = '[ğŸğŸ’¨ $version$workspace]($style) '

[username]
disabled = false
show_always = false
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '

[vagrant]
format = 'via [â± $version](bold white) '

[vlang]
disabled = true
format = 'via [V $version](blue bold) '

[vcsh]
format = '[ğŸ†… $repo](bold blue) '

[zig]
disabled = true
symbol = 'âš¡ï¸ '


# format = """
# $username\
# $hostname\
# $localip\
# $os\
# $container\
# $shlvl\
# $singularity\
# $kubernetes\
# $directory\
# $vcsh\
# $git_branch\
# $git_commit\
# $git_state\
# $git_status\
# $hg_branch\
# $docker_context\
# $package\
# $c\
# $cmake\
# $elm\
# $golang\
# $haskell\
# $haxe\
# $helm\
# $lua\
# $nim\
# $nodejs\
# $ocaml\
# $opa\
# $perl\
# $php\
# $pulumi\
# $python\
# $rlang\
# $ruby\
# $rust\
# $scala\
# $swift\
# $terraform\
# $vagrant\
# $buf\
# $nix_shell\
# $conda\
# $spack\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $azure\
# $env_var\
# $sudo\
# $cmd_duration\
# $line_break\
# $jobs\
# $time\
# $status\
# $shell\
# $character"""

